# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    # - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - binary: aws-resource-counter
    id: arc-others
    goos:
      - linux
  - binary: aws-resource-counter
    id: arc-macos
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - |
          sh -c '
          cat > /tmp/arc-{{ .Arch }}-gon.hcl <<EOF
          source = ["./dist/arc-macos_{{ .Target }}/{{ .Name }}"]
          bundle_id = "com.expel.aws-resource-counter"
          sign {
            application_identity = "71c685df24be2279027ca972134afd5c715ed841"
          }
          EOF
          '
        - "gon /tmp/arc-{{ .Arch }}-gon.hcl"
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
